In [3]:
import numpy as np

In [17]:
d_list = np.array([[1,2,7,3],[1,2,5,2],[1,1,2,3]])
hessian = [2,7,3,2]

np.sum(d_list*hessian*d_list, axis=1)

array([195, 113,  39])

In [41]:
# alpha = np.array([1,2])
alpha = np.array([1])
# S_list = np.array([[1,2,3] , [4,5,6]])
S_list = np.array([[1,2,3]])
np.sum(alpha*S_list.T , axis=1)

array([1, 2, 3])

In [58]:
m = 6

b = np.array([[2,3],[1,2]])
a = np.array([1,2,8,3,4,4,3,6])
print(type(a[-1]))

print(b[-1])
# print(a[-6])

<class 'numpy.int64'>
[1 2]


In [28]:
d_list = np.array([[1,2,0,0, 0] , [0,0,3 , 5, 0] , [0,0,0,0,6]])
dk_FW = np.array([1,2,3,4,5])
hessian = np.array([2,2,4,5,5])
c = 1 - np.array([0.9,0.8,0.5]) 
B = np.sum(d_list*hessian*d_list , axis=1)
A = np.sum(d_list*hessian*dk_FW ,axis = 1 )

print(A , B , c)

N = len(B)
alpha = [0]*N
alpha_sum = 0
for j in range(N) :
    alpha[N-1-j] =  -c[j]*B[j]/(A[j] + alpha_sum*B[j]*(c[j] - 1)) 
    alpha_sum = alpha_sum + 1/alpha[N-1-j]
alpha_0 = 1/(1+alpha_sum)
alpha = alpha_0 / alpha



[ 10 136 150] [ 10 161 180] [0.1 0.2 0.5]
0
0
1
1
2
2


In [21]:
a = np.array([1,2,3])


for j in range(2) :
    print(a[j])

1
2
